name: Jitsu 2.0 Build Docker Images
on:
  push:
    branches:
      # todo - change with main
      - feat/newjitsu/self-hosted-revamped
    tags:
      - jitsu2-*

jobs:
  build:
    name: Build Project
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/checkout@v3
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT


      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies with pnpm
        run: pnpm install --no-frozen-lockfile

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/jitsu2-')
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/jitsu2-}"

      - name: Build Beta Images
        if: github.ref == 'refs/heads/feat/newjitsu/self-hosted-revamped'
        run: pnpm build-scripts docker --tag beta --push-git-tag --push-docker --dry-run

      - name: Build Release Images
        if: startsWith(github.ref, 'refs/tags/jitsu2-')
        run: pnpm build-scripts docker --tag latest --version ${{ steps.version.outputs.version }} --push-git-tag --push-docker --dry-run
